#!/usr/bin/env python3

import sys
import subprocess
import os
import signal

HTTP_PREF = 'http://'
HTTP_PORT = '80'

HTTPS_PREF = 'https://'
HTTPS_PORT = '443'

LOCALHOST = '127.0.0.1:18081'

TEMPLATE = 'pid =\nforeground = yes\noutput = /dev/stdout\n[service]\nclient = yes\naccept = ' + LOCALHOST
FILE_NAME = 'config.txt'

def fatal(message):
    print('ERROR: ' + message, file=sys.stderr)
    sys.exit(1)

def get_server(prefix):
    address = sys.argv[2][(len(prefix)):]
    try:
        x = address.index('/')
        server = address[:x]
        port = server.find(':')
        # W razie potrzeby dodaj domyślny port.
        if port == -1:
            server = server + ':'
        port = server[(server.find(':') + 1):]
        if not port:
            if prefix == HTTP_PREF:
                server = server + HTTP_PORT
            elif prefix == HTTPS_PREF:
                server = server + HTTPS_PORT
    except:
        fatal('Wrong argument')
    return server

def signal_handler(sig, frame):
    try:
        os.remove(FILE_NAME)
    except:
        pass
    try:
        stunnel.kill()
    except:
        pass
    try:
        fnull.close()
    except:
        pass
    sys.exit(1)

def connect(server):
    subprocess.call(['./testhttp_raw', server, sys.argv[1], sys.argv[2]])

def make_config_file(server):
    config_file = open(FILE_NAME, 'w')
    print(TEMPLATE, file=config_file)
    print('connect = ' + server, file=config_file)
    config_file.close()

signal.signal(signal.SIGINT, signal_handler)

if len(sys.argv) != 3:
    fatal('Wrong number of arguments')


# Sprawdź, czy plik z ciasteczkami istnieje.
if not os.path.isfile(sys.argv[1]):
    fatal('There is no such file')

if sys.argv[2].startswith(HTTPS_PREF):
    server = get_server(HTTPS_PREF)
    make_config_file(server)
    fnull = open(os.devnull, 'w')
    stunnel = subprocess.Popen(['stunnel', FILE_NAME], stderr=fnull, stdout=subprocess.PIPE, universal_newlines=True)
    while True:
        line = stunnel.stdout.readline()
        if not line:
            break
        if line.find('Configuration successful'):
            break
    connect(LOCALHOST)
    stunnel.kill()
    os.remove(FILE_NAME)
    fnull.close()
elif sys.argv[2].startswith(HTTP_PREF):
    server = get_server(HTTP_PREF)
    connect(server)
else:
    fatal('Wrong argument')
